//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class RVprofile
{
    public RVprofile()
    {
        this.RVuser = new HashSet<RVuser>();
    }

    public string id { get; set; }
    public string name { get; set; }
    public string menu1 { get; set; }
    public string menu2 { get; set; }
    public string menu3 { get; set; }
    public string menu4 { get; set; }
    public string menu5 { get; set; }

    public virtual RVsub RVsub { get; set; }
    public virtual RVsub RVsub1 { get; set; }
    public virtual RVsub RVsub2 { get; set; }
    public virtual RVsub RVsub3 { get; set; }
    public virtual RVsub RVsub4 { get; set; }
    public virtual ICollection<RVuser> RVuser { get; set; }
}

public partial class RVsub
{
    public RVsub()
    {
        this.RVprofile = new HashSet<RVprofile>();
        this.RVprofile1 = new HashSet<RVprofile>();
        this.RVprofile2 = new HashSet<RVprofile>();
        this.RVprofile3 = new HashSet<RVprofile>();
        this.RVprofile4 = new HashSet<RVprofile>();
    }

    public string id { get; set; }
    public Nullable<bool> sub1 { get; set; }
    public Nullable<bool> sub2 { get; set; }
    public Nullable<bool> sub3 { get; set; }
    public Nullable<bool> sub4 { get; set; }
    public Nullable<bool> sub5 { get; set; }

    public virtual ICollection<RVprofile> RVprofile { get; set; }
    public virtual ICollection<RVprofile> RVprofile1 { get; set; }
    public virtual ICollection<RVprofile> RVprofile2 { get; set; }
    public virtual ICollection<RVprofile> RVprofile3 { get; set; }
    public virtual ICollection<RVprofile> RVprofile4 { get; set; }
}

public partial class RVuser
{
    public int id { get; set; }
    public string user { get; set; }
    public string name { get; set; }
    public string surname { get; set; }
    public string password { get; set; }
    public Nullable<bool> status { get; set; }
    public string idProfile { get; set; }

    public virtual RVprofile RVprofile { get; set; }
}
